---
services:
  postgres:
    image: "docker.io/postgres:18.4-alpine3.23"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      DATABASES_TO_CREATE: "iam,transactions"
    volumes:
    - "./postgres-init:/docker-entrypoint-initdb.d"
