/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

class MessageUtilsTest {
  @Test
  void testGetMessage() {
    assertThat("Hello      World!").isEqualTo(MessageUtils.getMessage());
  }
}
