---
name: "Qodana"
"on":
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
    - "master"
jobs:
  qodana:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      checks: "write"
    steps:
    - uses: "actions/checkout@v3"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
        fetch-depth: 0
    - name: "Qodana Scan"
      uses: "JetBrains/qodana-action@v2026.1"
      with:
        pr-mode: false
      env:
        QODANA_TOKEN: "${{ secrets.QODANA_TOKEN_930696827 }}"
        QODANA_ENDPOINT: "https://qodana.cloud"
        GH_TOKEN: "${{ secrets.GH_TOKEN }}"
